In [6]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,7,7.6,8,9],[54,23,34,54,56,0,0,0,0,0]])
print(arr)


[[ 1.   2.   3.   4.   5.   6.   7.   7.6  8.   9. ]
 [54.  23.  34.  54.  56.   0.   0.   0.   0.   0. ]]


In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5, 6, 7, 7.6, 8, 9],
    [54, 23, 34, 54, 56, 0, 0, 0, 0, 0]  # দুই লিস্টের দৈর্ঘ্য একই রাখা ভালো
])
print(arr)


[[ 1.   2.   3.   4.   5.   6.   7.   7.6  8.   9. ]
 [54.  23.  34.  54.  56.   0.   0.   0.   0.   0. ]]


In [ ]:
zeros=an.zeros((2,3))

In [7]:
# Zero matrix
zeros = np.zeros((2,3))
print("Zeros:\n", zeros)

# Ones matrix
ones = np.ones((2,3))
print("Ones:\n", ones)

# Identity matrix
identity = np.eye(3)
print("Identity:\n", identity)

# Range
range_arr = np.arange(0,10,2)
print("Range:\n", range_arr)

# Linspace
linspace_arr = np.linspace(0,1,5)
print("Linspace:\n", linspace_arr)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Range:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [8]:
zeros=np.zeros((3,3))

In [18]:
ones=np.ones((2,3))

In [19]:
identity = np.eye(3)

In [24]:
print("\n",zeros,"\n",ones,"\n",identity,"\n")


 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1.]
 [1. 1. 1.]] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [28]:
range_arr=np.arange(0,10,2)

In [29]:
print(range_arr)

[0 2 4 6 8]


In [31]:
linespace=np.linspace(0,1,5)

In [32]:
print(linespace)

[0.   0.25 0.5  0.75 1.  ]


In [33]:
print("shape:",arr.shape)

shape: (2, 10)


In [35]:
print("size",arr.size)

size 20


In [36]:
print(arr.dtype)

float64


In [37]:
print(arr.ndim)

2


In [42]:
a=np.array([1,3,5,6])
b=np.array([5,6,7,8])

In [43]:
a+b

array([ 6,  9, 12, 14])

In [44]:
a-b

array([-4, -3, -2, -2])

In [45]:
a*b

array([ 5, 18, 35, 48])

In [46]:
a/b

array([0.2       , 0.5       , 0.71428571, 0.75      ])

In [48]:
a**2

array([ 1,  9, 25, 36])

In [52]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.75680975, 2.82842712, 3.        ],
       [7.34846923, 4.79583152, 5.83095189, 7.34846923, 7.48331477,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [53]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 1.99819590e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.83075330e+23, 9.74480345e+09, 5.83461743e+14, 2.83075330e+23,
        2.09165950e+24, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00]])

In [54]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ,  0.96791967,  0.98935825,  0.41211849],
       [-0.55878905, -0.8462204 ,  0.52908269, -0.55878905, -0.521551  ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [55]:
print(arr[0])

[1.  2.  3.  4.  5.  6.  7.  7.6 8.  9. ]


In [62]:
print(arr[0:1])

[[1.  2.  3.  4.  5.  6.  7.  7.6 8.  9. ]]


Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951


In [71]:
arr=([15,16,17,18])
print(np.sum(arr))

66


In [72]:
print(np.max(arr))

18


In [73]:
maxx=np.max(arr)

In [75]:
print(maxx)

18


In [76]:
print(np.min(arr))

15


In [78]:
print(np.mean(arr))

16.5


In [79]:
print(np.std(arr))

1.118033988749895


In [89]:
np.random.rand(3,3)

array([[0.62685026, 0.60505595, 0.08108683],
       [0.93289214, 0.6472649 , 0.45851621],
       [0.12053882, 0.63910855, 0.82489314]])